s01/discussion/discussion/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('todolist/', include('todolist.urls')),
    path('admin/', admin.site.urls),
]

s01/discussion/todolist/urls.py
from django.urls import path

from . import views

'''
	path()
		Syntax:
			path(route, view, name)
'''
app_name = 'todolist'
urlpatterns = [
	# /todoitem route
	path('', views.index, name='index'),
	# /todoitem/<todoitem_id> route
	path('<int:todoitem_id>/', views.todoitem, name='viewtodoitem'),
	path('register/', views.register, name='register'),
	path('change_password/', views.change_password, name ='change_password'),
	path('login/', views.login_view, name='login'),
	path('logout/',views.logout_view, name='logout'),
	path('add_task/', views.add_task, name='add_task'),
	path('<int:todoitem_id>/edit', views.update_task, name='update_task'),
	path('<int:todoitem_id>/delete', views.delete_task, name='delete_task'),
	path('add_event/' ,views.add_event, name= 'add_event'),
	path('event/<int:event_id>/', views.event, name='viewevent'),
]

s01/discussion/todolist/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class ToDoItem(models.Model):
	task_name = models.CharField(max_length=50)
	description = models.CharField(max_length=200)
	status = models.CharField(max_length=50, default="pending")
	date_created = models.DateTimeField('date created')
	user = models.ForeignKey(User, on_delete=models.CASCADE, default="")

class Event(models.Model):
	event_name = models.CharField(max_length=50)
	event_description = models.CharField(max_length=200)
	event_status = models.CharField(max_length=50, default="pending")
	user = models.ForeignKey(User, on_delete=models.CASCADE, default="")

s01/discussion/todolist/forms.py
from django import forms

class LoginForm(forms.Form):
	username = forms.CharField(label = 'Username', max_length=20)
	password = forms.CharField(label='Password', max_length=20)

class AddTaskForm(forms.Form):
	task_name = forms.CharField(label='Task Name', max_length=50)	
	description = forms.CharField(label='Description', max_length=200)

class UpdateTaskForm(forms.Form):
	task_name = forms.CharField(label='Task Name', max_length=50)
	description = forms.CharField(label='Description', max_length=200)
	status = forms.CharField(label="Status", max_length=50)

class RegisterForm(forms.Form):
	username = forms.CharField(label = 'Username', max_length=20)
	first_name = forms.CharField(label='First Name', max_length=20)
	last_name = forms.CharField(label='Last Name', max_length=20)
	email = forms.CharField(label='Email', max_length=50)
	password = forms.CharField(label='Password', max_length=20)
	password2 = forms.CharField(label='Confirm password', max_length=20)

class AddEventForm(forms.Form):
	event_name = forms.CharField(label ='Event Name', max_length=50)
	event_description= forms.CharField(label = 'Description', max_length=200)
	

s01/discussion/todolist/views.py
from django.shortcuts import render, redirect, get_object_or_404
#from django.http import HttpResponse
#from django.template import loader
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.forms.models import model_to_dict
from django.utils import timezone
from django.contrib.auth.hashers import make_password


# Local imports
from .models import ToDoItem, Event
from .forms import LoginForm, AddTaskForm, UpdateTaskForm, RegisterForm, AddEventForm

# Create your views here.
def index(request):
	todoitem_list = ToDoItem.objects.filter(user_id=request.user.id)
	event_list = Event.objects.filter(user_id=request.user.id)
	context = {	'todoitem_list': todoitem_list , 'event_list': event_list}
	return render(request, "todolist/index.html", context)

def todoitem(request, todoitem_id):
	# retrieves the item object using the id or primary key
	todoitem = get_object_or_404(ToDoItem, pk=todoitem_id)

	# response = "You are viewing the details of %s"
	return render(request,"todolist/todoitem.html", model_to_dict(todoitem))


def register(request):
    context = {}

    if request.method == 'POST':
        form = RegisterForm(request.POST)

        if form.is_valid():
            username = form.cleaned_data['username']
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            password2 = form.cleaned_data['password2']

            # Check if a user with the same username or email already exists
            if User.objects.filter(username=username).exists() or User.objects.filter(email=email).exists():
                context={
                	"error":True,
                }
            else:
                # Hash the password
                hashed_password = make_password(password)

                # Create a new user and save
                user = User.objects.create(username=username, first_name=first_name, last_name=last_name, email=email, password=hashed_password)
                user.save()

                return redirect("todolist:login")
        else:
            # Form is not valid, so re-render the form with errors
            context['form'] = form
    else:
        # If it's not a POST request, create a new empty form
        form = RegisterForm()
        context['form'] = form

    return render(request, 'todolist/register.html', context)


def change_password(request):

	is_user_authenticated = False
	user = authenticate(username = "johndoe", password = "john1234")
	print(user)

	# Code here executes if the user is successfully authenticated
	if user is not None:
		authenticated_user = User.objects.get(username='johndoe')
		authenticated_user.set_password("johndoe1")
		authenticated_user.save()
		is_user_authenticated = True

	context = {
		"is_user_authenticated" : is_user_authenticated
	}

	return render(request,"todolist/change_password.html",context)

def login_view(request):
    # username = "johndoe"
    # password = "johndoe1"

    # user = authenticate(username=username, password=password)

    context = {}

    if request.method == 'POST':

    	form = LoginForm(request.POST)

    	if form.is_valid() == False:
    		# Returns a blank login form
    		form = LoginForm()
    	else:
    		# Retieves the information from the form
    		username = form.cleaned_data['username']
    		password = form.cleaned_data['password']
    		user = authenticate(username=username, password=password)
    		context = {
    			"username": username,
    			"password": password
    		}

    	if user is not None:
    		# Saves the user's ID in the session using Django's Session framework
    		login(request, user)
    		return redirect("todolist:index")
    	else:
    		# Provides context with error to conditionally render the error message
    		context = {
    			"error": True,
    		}

    return render(request, "todolist/login.html", context)

def logout_view(request):
	# Removes the saved data in session upon login
    logout(request)
    return redirect("todolist:index")


def add_task(request):
	context = {}

	if request.method == 'POST':

		form = AddTaskForm(request.POST)

		if form.is_valid() == False:
			form = AddTaskForm()
		else:
			task_name = form.cleaned_data['task_name']
			description = form.cleaned_data['description']  

			# Check the database if a task already exists
			duplicates = ToDoItem.objects.filter(task_name = task_name)

			if not duplicates:
				ToDoItem.objects.create(task_name=task_name, description=description, date_created=timezone.now(), user_id=request.user.id)

			else:
				context = {
					"error":True
				}

	return render(request, "todolist/add_task.html", context)

def update_task(request, todoitem_id):
	todoitem = ToDoItem.objects.filter(pk=todoitem_id)

	context ={
		"user": request.user,
		"todoitem_id": todoitem_id,
		"task_name": todoitem[0].task_name,
		"description": todoitem[0].description,
		"status": todoitem[0].status
	}		

	if request.method == 'POST':
		form = UpdateTaskForm(request.POST)

		if form.is_valid() == False:
			form = UpdateTaskForm()
		else:	
			task_name = form.cleaned_data['task_name']
			description = form.cleaned_data['description']
			status = form.cleaned_data['status']

			if todoitem:
				todoitem[0].task_name = task_name
				todoitem[0].description = description
				todoitem[0].status = status

				todoitem[0].save()

				return redirect("todolist:index")
			else:
				context = {
					"error": True
				}

	return render(request, "todolist/update_task.html", context)

def delete_task(request):
	todoitem = ToDoItem.objects.filter(pk=todoitem_id).delete()
	return redirect("todolist:index")


def add_event(request):
	context = {}

	if request.method == 'POST':

		form = AddEventForm(request.POST)

		if form.is_valid() == False:
			form = AddEventForm()
		else:
			event_name = form.cleaned_data['event_name']
			event_description = form.cleaned_data['event_description']  

			# Check the database if a task already exists
			duplicates = Event.objects.filter(event_name = event_name)

			if not duplicates:
				Event.objects.create(event_name=event_name, event_description=event_description, user_id=request.user.id)

			else:
				context = {
					"error":True
				}

	return render(request, "todolist/add_event.html", context)

def event(request, event_id):
	# retrieves the item object using the id or primary key
	event = get_object_or_404(Event, pk=event_id)

	# response = "You are viewing the details of %s"
	return render(request,"todolist/event.html", model_to_dict(event))

s01/discussion/todolist/templates/todolist/add_event.html
{% extends 'base.html' %}

{% block title %}Add Task{% endblock %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-6 offset-3">
        <h1 class="text-center my-3">Add A Event</h1>
        {% if error == True %}
          <p class="text-danger">Duplicate Event found</p>
        {% endif %}
        <form action="{% url 'todolist:add_event' %}" method="post">
          {% csrf_token %}

          <div class="mb-3">
              <label for="event_name">Event Name: </label>
              <input class="form-control" id="event_name" type="text" name="event_name" value="{{ event_name }}" maxlength="50" required>
          </div>

          <div class="mb-3">
              <label for="event_description">Description: </label>
              <textarea class="form-control" name="event_description" value="{{ event_description }}" required></textarea>
          </div>

          <div class="text-center">
              <input class="btn btn-success" type="submit" value="Add Event">
          </div>

        </form>
      </div>
    </div>
  </div>
{% endblock %}

s01/discussion/todolist/templates/todolist/add_task.html
{% extends 'base.html' %}

{% block title %}Add Task{% endblock %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-6 offset-3">
        <h1 class="text-center my-3">Add A Task</h1>
        {% if error == True %}
          <p class="text-danger">Duplicate task found</p>
        {% endif %}
        <form action="{% url 'todolist:add_task' %}" method="post">
          {% csrf_token %}

          <div class="mb-3">
              <label for="task_name">Task Name: </label>
              <input class="form-control" id="task_name" type="text" name="task_name" value="{{ task_name }}" maxlength="50" required>
          </div>

          <div class="mb-3">
              <label for="description">Description: </label>
              <textarea class="form-control" name="description" value="{{ description }}" required></textarea>
          </div>

          <div class="text-center">
              <input class="btn btn-success" type="submit" value="Add Task">
          </div>

        </form>
      </div>
    </div>
  </div>
{% endblock %}

s01/discussion/todolist/templates/todolist/change_password.html
{% if is_user_authenticated == False %}
	<h1>Invalid User Credentials</h1>
	<p>Check if the username and password is correct</p>
{% else %}
	<h1>User Password Successfully Updated!</h1>
	<p>The password has been successfully updated</p>
{% endif %}		

s01/discussion/todolist/templates/todolist/event.html
{% extends 'base.html' %}

{% block title %}My Events{% endblock %}

{% block content %}
<div class="text-center my-3">
	<h1>{{ event_name }}</h1>
	<h3>Description</h3>
	<p>{{ event_description }}</p>
	<h3>Status</h3>
	<p>{{ event_status }}</p>
	
</div>

{% endblock %}

s01/discussion/todolist/templates/todolist/index.html
{% extends 'base.html'%}

{% block title %} Home {% endblock %}

{% block content %}
    {% if todoitem_list and not user.is_anonymous %}
        <h1 class = "text-center my-3"> Welcome {{user.first_name}} {{user.last_name}}!</h1>
        <div class= "container">
            <div class = "row">
                <h3 class = "text-center mb-3"> My Tasks </h3>
                <ul class = "list-group col-lg-2 offset-lg-5 text-center">    
                    {% for todoitem in todoitem_list %}
                    <a href="{% url 'todolist:viewtodoitem' todoitem.id %}" class="text-decoration-none">
                        <li class ="list-group-item">{{ todoitem.task_name }}</li>
                    </a>
                    {% endfor %}
                </ul>   
            </div>  
            <div class="container">
            <div class="row">
                <h3 class="text-center mb-3"> My Events </h3>
                <ul class="list-group col-lg-2 offset-lg-5 text-center">
                    {% for event in event_list %}
                    <a href="{% url 'todolist:viewevent' event.id %}" class="text-decoration-none">
                        <li class="list-group-item">{{ event.event_name }}</li>
                    </a>
                    {% endfor %}
                </ul>
            </div>
        </div>
    {% elif user.is_anonymous == True %}
        <h1 class="text-center my-3">You are not authorized to access this page</h1>
        <p class = "text-center">Kindly login <a href = "{% url 'todolist:login' %}">here </p>
    {% else %} 
        <p>No tasks have been created</p>
    {% endif %}
{% endblock %}    

s01/discussion/todolist/templates/todolist/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-6 offset-3">
      <h1 class="text-center my-3">Login</h1>
      {% if error == True %}
        <p class="text-danger">Invalid user credentials, please check your username and password</p>
      {% endif %}
      <form action="{% url 'todolist:login' %}" method="post">
        <!-- This template tag provides protection against Cross Site Request Forgeries (CSRF) -->
        <!-- CSRF occurs when a malicious website contains a link, a form button or some JavaScript that is intended to perform some action our website, using the credentials of a logged-in user -->
        {% csrf_token %}

        <div class="mb-3">
            <label for="username">Username: </label>
            <input class="form-control" id="username" type="text" name="username" value="{{ username }}" maxlength="20" required>
        </div>

        <div class="mb-3">
            <label for="password">Password: </label>
            <input class="form-control" id="password" type="password" name="password" value="{{ password }}" maxlength="20" required>
        </div>

        <div class="text-center">
            <input class="btn btn-success" type="submit" value="Login">
        </div>

      </form>
    </div>
  </div>
</div>

{% endblock %}

s01/discussion/todolist/templates/todolist/register.html
{% extends 'base.html' %}

{% block title %}Register{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-6 offset-3">
      <h1 class="text-center my-3">Register</h1>
      {% if error == True %}
        <p class="text-danger">User already exists, please choose a different username or email</p>
      {% endif %}
      <form action="{% url 'todolist:register' %}" method="post">
        <!-- This template tag provides protection against Cross Site Request Forgeries (CSRF) -->
        <!-- CSRF occurs when a malicious website contains a link, a form button or some JavaScript that is intended to perform some action on our website, using the credentials of a logged-in user -->
        {% csrf_token %}

        <div class="mb-3">
            <label for="username">Username: </label>
            <input class="form-control" id="username" type="text" name="username" value="{{ username }}" maxlength="20" required>
        </div>

        <div class="mb-3">
            <label for="first_name">First Name: </label>
            <input class="form-control" id="first_name" type="text" name="first_name" value="{{ first_name }}" maxlength="30" required>
        </div>

        <div class="mb-3">
            <label for="last_name">Last Name: </label>
            <input class="form-control" id="last_name" type="text" name="last_name" value="{{ last_name }}" maxlength="30" required>
        </div>

        <div class="mb-3">
            <label for="email">Email: </label>
            <input class="form-control" id="email" type="email" name="email" value="{{ email }}" maxlength="100" required>
        </div>

        <div class="mb-3">
            <label for="password">Password: </label>
            <input class="form-control" id="password" type="password" name="password" maxlength="20" required>
        </div>

        <div class="mb-3">
            <label for="password2">Confirm Password: </label>
            <input class="form-control" id="password2" type="password" name="password2" maxlength="20" required>
        </div>

        <div class="text-center">
            <input class="btn btn-success" type="submit" value="Register">
        </div>

      </form>
    </div>
  </div>
</div>

{% endblock %}

s01/discussion/todolist/templates/todolist/todoitem.html
{% extends 'base.html' %}

{% block title %}To Do Item{% endblock %}

{% block content %}
<div class="text-center my-3">
	<h1>{{ task_name }}</h1>
	<h3>Description</h3>
	<p>{{ description }}</p>
	<h3>Status</h3>
	<p>{{ status }}</p>
	
	<button class="btn btn-primary mx-1 text-decoration-none">
		<a href="{% url 'todolist:update_task' id %}" class="text-light text-decoration-none">Edit Task</a>
	</button>

	<button class="btn btn-danger mx-1 text-decoration-none">
		<a href="{% url 'todolist:delete_task' id %}" class="text-light text-decoration-none">Delete Task</a>
	</button>

	<button class="btn btn-warning mx-1 text-decoration-none">
		<a href="{% url 'todolist:index' %}" class="text-light text-decoration-none">Back To Tasks</a>
	</button>
	
</div>

{% endblock %}

s01/discussion/todolist/templates/todolist/update_task.html
{% extends 'base.html' %}

{% block title %}Update Task{% endblock %}

{% block content %}
  {% if user.is_anonymous == False %}
  <div class="container">
    <div class="row">
      <div class="col-6 offset-3">
        <h1 class="text-center my-3">Update Task</h1>
        {% if error == True %}
          <p class="text-danger">Task not found</p>
        {% endif %}
        <form action="{% url 'todolist:update_task' todoitem_id %}" method="post">
          {% csrf_token %}

          <div class="mb-3">
              <label for="task_name">Task Name: </label>
              <input class="form-control" id="task_name" type="text" name="task_name" value="{{ task_name }}" maxlength="50" required>
          </div>

          <div class="mb-3">
              <label for="description">Description: </label>
              <textarea class="form-control" name="description" required>{{ description }}</textarea>
          </div>

          <div class="mb-3">
              <label for="status">Status: </label>
              <input class="form-control" id="status" type="text" name="status" value="{{ status }}" maxlength="50" required>
          </div>

          <div class="text-center">
              <input class="btn btn-success" type="submit" value="Update Task">
          </div>

        </form>
      </div>
    </div>
  </div>
  {% else %}
    <h1 class="text-center my-3">You are not authorized to access this page.</h1>
    <p class="text-center">Kindly login <a href="{% url 'todolist:login' %}">here</a></p>
  {% endif %}
{% endblock %}